USE [master]
GO
/****** Object:  Database [RoofstockDB]    Script Date: 7/4/2021 7:47:55 ******/
CREATE DATABASE [RoofstockDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RoofstockDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RoofstockDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RoofstockDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RoofstockDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RoofstockDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RoofstockDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RoofstockDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RoofstockDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RoofstockDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RoofstockDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RoofstockDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RoofstockDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RoofstockDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RoofstockDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RoofstockDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RoofstockDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RoofstockDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RoofstockDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RoofstockDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RoofstockDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RoofstockDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RoofstockDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RoofstockDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RoofstockDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RoofstockDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RoofstockDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RoofstockDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RoofstockDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RoofstockDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RoofstockDB] SET  MULTI_USER 
GO
ALTER DATABASE [RoofstockDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RoofstockDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RoofstockDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RoofstockDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RoofstockDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RoofstockDB] SET QUERY_STORE = OFF
GO
USE [RoofstockDB]
GO
/****** Object:  Table [dbo].[Properties]    Script Date: 7/4/2021 7:47:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Properties](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RawId] [int] NOT NULL,
	[Address] [varchar](250) NOT NULL,
	[YearBuilt] [int] NOT NULL,
	[ListPrice] [decimal](18, 2) NOT NULL,
	[MonthlyRent] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Propertie] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RoofstockDB] SET  READ_WRITE 
GO